### ISSUE TITLE
Exception: Could not match http_address: 10.10.10.45:9200

### ISSUE THREAD

**Issue by scottleibrand** [vertical-knowledge/rollastic#11]
It appears that our version of ES (Version: 2.3.3, Build: 218bdf1/2016-05-17T15:40:04Z, JVM: 1.8.0_51) is returning nodes formatted differently than rollastic expects, resulting in :

```
  File "/usr/local/lib/python2.7/dist-packages/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/cluster.py", line 52, in __init__
    master_hosts.append(node.publish_host)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/node.py", line 124, in publish_host
    raise Exception('Could not match http_address: %s' % http_addr)
Exception: Could not match http_address: 10.10.10.45:9200
```

I can't quite parse the regex in line 124, so I'm not quite sure what it's expecting, or how we'd modify the regex to support the `10.10.10.45:9200` format.

Thoughts?

**Comment by akatrevorjay** [comment]
Hi @scottleibrand ! Author here. I've pushed a fix to the hotfix branch below.

Do you mind testing it out and if it works I'll make a release?

https://github.com/akatrevorjay/rollastic/tree/hotfix/elastic-2.3

You can also install this locally via pip via:

``` sh
pip install -e git+https://github.com/akatrevorjay/rollastic@hotfix/elastic-2.3#egg=rollastic
```

We run earlier versions of Elastic at this point in time, which is why I'm holding off on the release before you give the final OK.

Thanks for the report!

**Comment by scottleibrand** [comment]
Different error this time.  Am I doing something else wrong? 

```
root@salt:/srv/salt# rollastic restart 10.10.10.45
2016-07-07 12:36:26,772| rollastic.__main__/MainProcess[8330]-MainThread: Rolling restart with master_node=10.10.10.45 kill_at_heap=85 @restart:44 #INFO
2016-07-07 12:36:26,773| rollastic.cluster/MainProcess[8330]-MainThread: Connecting to all master nodes @__init__:48 #INFO
2016-07-07 12:36:26,795| salt.log.setup/MainProcess[8330]-MainThread: An un-handled exception was caught by salt's global exception handler:
KeyError: 'master'
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/cluster.py", line 51, in __init__
    if node.is_master:
  File "/usr/local/lib/python2.7/dist-packages/rollastic/node.py", line 88, in is_master
    return self['settings']['node']['master'] == 'true'
KeyError: 'master' @__global_logging_exception_handler:713 #ERROR
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/cluster.py", line 51, in __init__
    if node.is_master:
  File "/usr/local/lib/python2.7/dist-packages/rollastic/node.py", line 88, in is_master
    return self['settings']['node']['master'] == 'true'
KeyError: 'master'
root@salt:/srv/salt#
```

**Comment by akatrevorjay** [comment]
Hi Scott,

You're not doing anything wrong, I just haven't updated this for Elastic
2.3 as of yet. In the past there are only a few slight differences, which
appears to be the case here as well. In this case, they modified the way it
declares if it's a master node or not.

I was hoping that the http_address was all that had changed. Looks like
there are a couple more schema differences. I'll start one with Docker and
will compare them both in a bit!

Thanks,
Trevor

Thanks,
Trevor

**Comment by scottleibrand** [comment]
Ok, cool.  LMK if there's anything else you'd like me to run.  This is a lab environment, so it's not too intrusive to do restarts whenever I want.  :-)

FWIW, I ended up scripting something directly in salt to accomplish what we needed last week, so there's no longer any urgency on my part.

**Comment by akatrevorjay** [comment]
Hi @scottleibrand ,

Oh ok, thanks for the info.

I've gotten it working against my little lab setup using the latest in the previously mentioned branch. From what I can see, Elastic only gives out the info if a node is `master`/`data` if it's configured now it seems, which is quite odd of a change.

Feel free to give it a go, just make sure to `pip uninstall rollastic` before the `pip install` command from earlier.

**Comment by scottleibrand** [comment]
```
root@salt:/srv/salt# pip uninstall rollastic
Can't uninstall 'rollastic'. No files were found to uninstall.
root@salt:/srv/salt# pip install -e git+https://github.com/akatrevorjay/rollastic@hotfix/elastic-2.3#egg=rollastic
Obtaining rollastic from git+https://github.com/akatrevorjay/rollastic@hotfix/elastic-2.3#egg=rollastic
  Updating ./src/rollastic clone (to hotfix/elastic-2.3)
  Running setup.py (path:/srv/salt/src/rollastic/setup.py) egg_info for package rollastic

  Installing extra requirements: 'egg'
Requirement already satisfied (use --upgrade to upgrade): elasticsearch in /usr/local/lib/python2.7/dist-packages (from rollastic)
Requirement already satisfied (use --upgrade to upgrade): click in /usr/local/lib/python2.7/dist-packages (from rollastic)
Requirement already satisfied (use --upgrade to upgrade): salt in /usr/lib/python2.7/dist-packages (from rollastic)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from rollastic)
Installing collected packages: rollastic
  Running setup.py develop for rollastic

    Creating /usr/local/lib/python2.7/dist-packages/rollastic.egg-link (link to .)
    rollastic 0.0.7 is already the active version in easy-install.pth
    Installing rollastic script to /usr/local/bin

    Installed /srv/salt/src/rollastic
Successfully installed rollastic
Cleaning up...
root@salt:/srv/salt# rollastic restart 10.10.10.45
2016-07-08 14:53:45,309| rollastic.__main__/MainProcess[6218]-MainThread: Rolling restart with master_node=10.10.10.45 kill_at_heap=85 @restart:44 #INFO
2016-07-08 14:53:45,310| rollastic.cluster/MainProcess[6218]-MainThread: Connecting to all master nodes @__init__:48 #INFO
^C
Aborted!
```

That was after 10+ minutes of no apparent activity.

**Comment by akatrevorjay** [comment]
Hi Scott, can you add the port to the node IP? IE :9200

**Comment by scottleibrand** [comment]
That node was down.  Restarted it, and back to the same stuff as before:

```
2016-07-08 16:01:13,157| salt.log.setup/MainProcess[18809]-MainThread: An un-handled exception was caught by salt's global exception handler:
KeyError: 'master'
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/cluster.py", line 51, in __init__
    if node.is_master:
  File "/usr/local/lib/python2.7/dist-packages/rollastic/node.py", line 88, in is_master
    return self['settings']['node']['master'] == 'true'
KeyError: 'master' @__global_logging_exception_handler:713 #ERROR
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/usr/local/lib/python2.7/dist-packages/rollastic/cluster.py", line 51, in __init__
    if node.is_master:
  File "/usr/local/lib/python2.7/dist-packages/rollastic/node.py", line 88, in is_master
    return self['settings']['node']['master'] == 'true'
KeyError: 'master'
```

**Comment by akatrevorjay** [comment]
Hi Scott,

That code is only in the old version, it looks like you hit pip's caching.
I'm on the road, but I believe adding -U to the pip install command should
be all that you need to do to get the latest from that branch.

Sorry about that!
Trevor

**Comment by scottleibrand** [comment]
That upgraded all the dependencies, but didn't change rollastic itself AFAICT, and the error is still there.

This is also odd:

root@salt:/srv/salt# pip uninstall rollastic
Can't uninstall 'rollastic'. No files were found to uninstall.

No rush, we can pick this up next week or whenever's convenient for you.

**Comment by akatrevorjay** [comment]
Hi Scott,

You've entered the land of pip caching purgatory. You see a small bit of
light at the end of the tunnel. You have some snake venom in your satchel.

Kidding aside, this should definitely fix pip's horrid git repo caching:

find /usr/local -type d -name rollastic -exec rm -rfv '{}' ';'

Then run that pip install command again.

Sorry about that! I should have asked you to do it in a virtualenv with
--system-site-packages, but no worries.

**Comment by scottleibrand** [comment]
LOL, so true.  :-)

That seemed to work.  Now:

```
root@salt:/srv/salt# rollastic restart 10.10.10.45
2016-07-08 17:07:01,709| rollastic.__main__/MainProcess[496]-MainThread: Rolling restart with master_node=10.10.10.45 kill_at_heap=85 @restart:44 #INFO
2016-07-08 17:07:01,710| rollastic.cluster/MainProcess[496]-MainThread: Connecting to all master nodes @__init__:48 #INFO
2016-07-08 17:07:01,727| salt.log.setup/MainProcess[496]-MainThread: An un-handled exception was caught by salt's global exception handler:
KeyError: 'http_address'
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/srv/salt/src/rollastic/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/srv/salt/src/rollastic/rollastic/cluster.py", line 52, in __init__
    master_hosts.append(node.publish_host)
  File "/srv/salt/src/rollastic/rollastic/node.py", line 121, in publish_host
    http_addr = self['http_address']
KeyError: 'http_address' @__global_logging_exception_handler:1032 #ERROR
Traceback (most recent call last):
  File "/usr/local/bin/rollastic", line 9, in <module>
    load_entry_point('rollastic==0.0.7', 'console_scripts', 'rollastic')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/srv/salt/src/rollastic/rollastic/__main__.py", line 46, in restart
    cluster = Cluster(master_node)
  File "/srv/salt/src/rollastic/rollastic/cluster.py", line 52, in __init__
    master_hosts.append(node.publish_host)
  File "/srv/salt/src/rollastic/rollastic/node.py", line 121, in publish_host
    http_addr = self['http_address']
KeyError: 'http_address'
root@salt:/srv/salt#
```

**Comment by akatrevorjay** [comment]
Hi Scott,

I started to write a debugging utility, but Im currently moving so its
taken second priority.

Do you mind posting the output of the cluster node stats and info commands?
Feel free to email them instead @ github@trevor.joynson.io

I ask because my clusters all have that entry and I would like to compare ;)

Thanks,
Trevor

**Comment by scottleibrand** [comment]
Ok, let's pick this back up after your move then.  It's not a super high priority for me either.
